# Generated by Django 6.1 on 2026-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Type1'), (2, 'Type2'), (3, 'Type3'), (4, 'Type4'), (5, 'Type5')])),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
