# Generated by Django 6.1 on 2026-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointfeature',
            name='date_create',
            field=models.DateField(),
        ),
    ]
